### ISSUE TITLE
Prepare package for public release

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot-plugin-secrets-providers#11]
-  [x] Update Dockerfile and invoke versions for v1.2.0 when it is released.
-  [x] Update GH actions to use v1.2.0
-  [x] Implement a `CHANGELOG.md` if we aren't gonna do docs
-  [x] Perform a `poetry update` prior to final release

**Comment by ubajze** [comment]
@jathanism the pipeline is prepared. I merged changes to the `develop` branch. Once you are ready, move these changes to the `main` branch and create a new release. If you need any help, let me know.

FYI: @jedelman8
