### ISSUE TITLE
Add Thycotic Secret Server plugin

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot-plugin-secrets-providers#21]
### Environment
* Nautobot version:   1.2.4
* secrets version:   1.0.0

### Proposed Functionality

Add a plugin to support Thycotic Secret Server

### Use Case

Use Thycotic Secret Server as a plugin to query for usernames, passwords, ...

**Comment by jifox** [comment]
I've already a running implementation on my development environment but struggling to integrate with the development environment in this repository

**Comment by bryanculver** [comment]
Added via #22
