### ISSUE TITLE
Allow AWS/K8s Authentication methods for Vault

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-secrets-providers#34]
### Environment
* Nautobot version:  1.3.7
* secrets version:  1.2.0

### Proposed Functionality

Hashicorp Vault has several other authentication methods which can be used to authenticate against Vault.  The 2 I am proposing here are AWS and Kubernetes.  It is possible Nautobot running on an EC2 instance could inherit an IAM role and use that to authenticate to Vault.  Similarly it's possible if Nautobot is running in Kubernetes it could use the service account associated with the pod to authenticate.

### Use Case

As an SRE I would like to leverage some other authentication methods built in to Vault which do not require a token or an app id.

**Comment by glennmatthews** [comment]
Implemented in #35 and #36.
